-- Onda 3 / ADR-005: transactional outbox for staged checkout (idempotent on AGGREGATE_ID + EVENT_TYPE)
CREATE TABLE IF NOT EXISTS CHECKOUT_OUTBOX (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AGGREGATE_ID VARCHAR(64) NOT NULL,
  EVENT_TYPE VARCHAR(64) NOT NULL,
  PAYLOAD TEXT NOT NULL,
  STATUS VARCHAR(16) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  PROCESSED_AT TIMESTAMP NULL,
  UNIQUE KEY UK_OUTBOX_AGG_TYPE (AGGREGATE_ID, EVENT_TYPE)
);
