server.port=8084

spring.application.name=search-service

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.ping.enabled=true

spring.main.allow-bean-definition-overriding=true

search-service.internal.token=${SEARCH_INTERNAL_TOKEN:dev-search-token}

search.credentials.username=${SEARCH_USERNAME:admin}
search.credentials.password=${SEARCH_PASSWORD:admin}
search.clusterName=opensearch-cluster
search.searchLanguages=en,fr
search.host[0].scheme=http
search.host[0].host=${SEARCH_HOST:127.0.0.1}
search.host[0].port=${SEARCH_PORT:9200}
search.noindex=false
